version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./akash:/root/akash
      - bundle_cache:/usr/local/bundle:delegated
    ports:
      - "3000:3000"
    env_file:
      - '.env'


volumes:
  bundle_cache:
    driver: local
